### ISSUE TITLE
Problème d'affichage de ventes multiples pour une parcelle

### ISSUE THREAD

**Issue by Naxxos** [marion-paclot/DVF#1]
Lors de la sélection d'une parcelle ayant eu plusieurs vente sur la période donnée, toutes les ventes s'affichent avec les mêmes valeur en prix d'achat et date de vente. Les surfaces des biens semblent correctes quand il y a différents bien vendus dans cette parcelle.

**Comment by marion-paclot** [comment]
Bonjour Naxxos, et après avoir vidé le cache ? Normalement ça devrait fonctionner. Merci

**Comment by Naxxos** [comment]
C'est bon !
