### ISSUE TITLE
Les données de Mayotte ainsi que de l'Alsace sont manquantes.

### ISSUE THREAD

**Issue by forestier** [marion-paclot/DVF#11]
Bonjour,

Y-a-t-il une explication concernant le fait que "Les données de Mayotte ainsi que de l'Alsace sont manquantes." ?

Merci.

**Comment by marion-paclot** [comment]
Bonjour, 
Certains départements ne sont pas cadastrés. Les mutations présentes dans DVF étant identifiées par leur parcelle cadastrale (entre autre), je suppose que c'est la raison pour laquelle il n'y a pas de données (y compris en base, indépendamment de l'application) concernant ces départements.

**Comment by jdesboeufs** [comment]
Je me permets de compléter la réponse.

La DGFiP qui produit les données DVF ne dispose pas des mutations des départements du Bas-Rhin, Haut-Rhin, Moselle et Mayotte. Pour l'ancienne Alsace-Moselle les données sont dans le Livre Foncier  en raison de l'application du droit local, et ne sont actuellement pas ouvertes.
Pour Mayotte, je n'ai pas la réponse, mais ce n'est un département que depuis peu.

Par ailleurs pour les milliers de communes qui ne disposent pas encore d'un cadastre vectoriel, cet outil n'est actuellement pas en mesure d'afficher quoi que ce soit. Ce dernier point pourrait évoluer.

**Comment by forestier** [comment]
Bonjour,

Je pense effectivement que c'est lié au droit local et non à un problème de cadastre, l'Alsace étant disponible ici : https://www.cadastre.gouv.fr/

> La base de données DVF concerne l’ensemble du territoire de
> la France métropolitaine, hors Alsace et Moselle (qui relèvent
> du « livre foncier »), ainsi que les Départements et Régions
> d’Outre-Mer (DROM), excepté Mayotte. 

source : http://www.epf.alsace/ressources-documentaires/les-incontournables-du-foncier/37-guide-dvf/file.html
