### ISSUE TITLE
Alsace manquante 

### ISSUE THREAD

**Issue by samy** [marion-paclot/DVF#17]
Merci pour ce super boulot !
J'ai diffusé en interne l'outil et on m'a signalé que l'Alsace manquait. (on a bien les parcelles cadastrales mais pas de valeurs foncières derrière) 

Mais je ne sais pas si le jeu de données initial comporte ces données

**Comment by Naxxos** [comment]
En effet, il est précisé que "La base de données « Demandes de valeurs foncières », ou DVF, recense l’ensemble des ventes de biens fonciers réalisées au cours des cinq dernières années, en métropole et dans les départements et territoires d’outre-mer — sauf à Mayotte et en Alsace-Moselle" sur le site https://cadastre.data.gouv.fr/dvf

**Comment by samy** [comment]
> En effet, il est précisé que "La base de données « Demandes de valeurs foncières », ou DVF, recense l’ensemble des ventes de biens fonciers réalisées au cours des cinq dernières années, en métropole et dans les départements et territoires d’outre-mer — sauf à Mayotte et en Alsace-Moselle" sur le site https://cadastre.data.gouv.fr/dvf

Merci !
