### ISSUE TITLE
Remplissage SQL à partir des données DGFIP

### ISSUE THREAD

**Issue by sven337** [marion-paclot/DVF#19]
Les données DVF sont livrées dans un format texte, mais l'application semble parler à une base SQL. Avez-vous prévu de publier  le script qui crée la base SQL à partir des  données source ?

**Comment by marion-paclot** [comment]
C'est envisageable sans trop de travail, mais un membre de l'équipe ayant retravaillé les données de manière beaucoup plus complète et en ayant fait d'autres choix, il faut qu'on s'accorde sur ce que l'on fait ;)

**Comment by cerisara** [comment]
Comment peut-on recréer la base SQL à partir des fichiers txt ? Le code pour créer la base est-il disponible ? (Sinon, l'appli n'est pas vraiment utilisable)

Merci !

**Comment by marion-paclot** [comment]
Que se passe t-il avec l'appli ? En fait on l'a pensé pour ordinateur et pas vraiment pour mobile, mais en format paysage ça passe.

**Comment by marion-paclot** [comment]
Bon, je vais mettre le code actuel en ligne, on modifiera plus tard tout ça quand j'aurais tranché le cas mentionné ci-dessus

**Comment by marion-paclot** [comment]
C'est fait.
