### ISSUE TITLE
Panneau latéral droit des informations cache les lignes cadastrales

### ISSUE THREAD

**Issue by iceman60** [marion-paclot/DVF#22]
Sur mobile le panneau latéral droit des informations meme s’il n’est pas affiché cache les parcelles et il ne reste qu’un seul petit bandeau à gauche pour pouvoir visualiser les parcelles.
![5487C916-BC1E-4364-BA91-A6D927E19973](https://user-images.githubusercontent.com/4654408/56861134-77f7f980-699e-11e9-9b57-50d1deace5b1.png)

**Comment by marion-paclot** [comment]
Normalement, le problème est résolu. Tenez moi au courant et merci du signalement.

**Comment by iceman60** [comment]
C'est tout bon pour moi, merci a vous pour votre réactivité!
