### ISSUE TITLE
Erreur javascript - compatibilité

### ISSUE THREAD

**Issue by michel-maier** [marion-paclot/DVF#23]
Rien à faire l'appli ne fonctionne pas sur ma machine.
FEDORA 29
Chrome Version 74.0.3729.108 (Build officiel) (64 bits)

Si **etalab** est un service de l'état il se doit d'être accessible.

**Object.keys(json[0])**

```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at exportCSV (index.js?version=1:125)
    at HTMLAnchorElement.onclick ((index):1)
```

```
function exportCSV(el, data, fileName) {
	
	var json = data;
	var fields = Object.keys(json[0])
	var replacer = function(key, value) { return value === null ? '' : value } 
	var csv = json.map(function(row){
	  return fields.map(function(fieldName){
		return JSON.stringify(row[fieldName], replacer)
	  }).join(';')
	})
	csv.unshift(fields.join(';')); // add header column
	csv = csv.join('\r\n');
	
	el.setAttribute("href", "data:text/csv;charset=utf-8," + encodeURIComponent(csv));
	el.setAttribute("download", fileName);
}
```

**Je vois également des console.log trainés un peu pas partout, il me semble que ça casse la compatibilité avec certain navigateur.**

**Comment by Neofox** [comment]
Même soucis, l'application ne fonctionne pas sur ma machine 
MacOS 10.14.4 et Windows 10

```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at exportCSV (index.js?version=1:125)
    at HTMLAnchorElement.onclick ((index):1)
```

**Comment by fm89** [comment]
J'ai effectivement la même anomalie que vous quand je cherche à télécharger le fichier CSV des transactions pour un couple (section, plage temporelle) pour lequel la base **ne contient pas de transaction**. En revanche, le téléchargement fonctionne bien dès qu'il y a au moins une transaction (parcelle coloriée en bleu).

**Comment by Neofox** [comment]
Peut être que la non disponibilité d'une transaction devrait être signalé.
Habitant en Alsace (et si j'ai bien compris il n'y a pas de données en Alsace/Moselle/Mayotte ce qui expliquerait l'erreur)  impossible de faire fonctionner l'application pour ma part. Mes proches ayant eux aucunes connaissances dans le développement web ne voient simplement qu'une application qui ne fonctionne pas

**Comment by marion-paclot** [comment]
> Si **etalab** est un service de l'état il se doit d'être accessible.

Alors en fait oui pour ce qui est du SPD (et DVF n'en fait pas partie), mais pas pour une application qui est une **réutilisation**. 
Cette application n'est en aucun cas le produit définit légalement par décret. Mais nous allons corriger ce bug très vite.

**Comment by marion-paclot** [comment]
Le bug est corrigé. Dites moi si ça fonctionne et je ferme l'issue. Par contre j'insiste, il ne faut pas confondre l'obligation légale de mise à disposition des données, et l'application grand public (on a eu 250k visiteurs en 2 jours) qui est faite de manière très contrainte (vous noterez les commits la nuit et le WE) pour que le grand public y ait accès, mais qui relève (malheureusement sans doute) du bonus.

**Comment by Neofox** [comment]
@marion-paclot parfait pour moi merci ! 
C'est une bonne choses que ces données soit mis à disposition à travers ces nouveaux outils, car pour la grande majorité des personnes (moi y compris) c'est une des façon les plus simple d'accéder à toutes ces informations. 
Petite question au passage, les données pour l'alsace-moselle-mayotte seront disponibles un jour ou ce n'est simplement pas possible ?

Merci de votre réactivité en tout cas.

**Comment by marion-paclot** [comment]
@jdesboeufs sera plus précis que moi (tu corriges si je dis encore une bétise) : pour Haut et Bas Rhin ainsi que Moselle, c'est historique - en gros les mutations ne sont pas remontée à la base centrale. Pour Mayotte c'est peut-être du à la "récente" (10 ans quand même) intégration dans la famille des départements. Donc malheureusement, je n'espère rien pour aucun des 4 dans un avenir proche...

**Comment by Neofox** [comment]
Merci pour ces informations supplémentaire en tout cas !
