### ISSUE TITLE
Sols en " nan m² "

### ISSUE THREAD

**Issue by jbledevehat** [marion-paclot/DVF#29]
La parcelle à Vaires-sur-Marne (77360) N°77479000AM0004 affiche pour les appartements un sols dont la valeur est "nan m²"

**Comment by marion-paclot** [comment]
Merci d'en avoir retrouvé une, j'avais vu ce pb sans noter la parcelle. On a encore pas mal de boulot ;)

**Comment by marion-paclot** [comment]
Corrigé. Le temps que le cache se vide (ou que je le vide)
