### ISSUE TITLE
Boutton A propos non fonctionnel

### ISSUE THREAD

**Issue by ekingr** [marion-paclot/DVF#4]
Bonjour,

Le bouton _A propos_ dans le bandeau d’entête ne fonctionne pas.
Quand on le clique l'URL change en `https://app.dvf.etalab.gouv.fr/#about` mais rien n’apparaît.
Testé sous Firefox 66 et Chrome 73.

Cordialement,

Guillaume

**Comment by marion-paclot** [comment]
Bonjour Guillaume, 
En effet, il n'y a rien derrière pour le moment, j'ai manqué de temps pour finir les choses moins techniques (comme une doc ...). ça ne saurait tarder. Merci d'avoir testé avec deux navigateurs cependant :D

**Comment by marion-paclot** [comment]
Une FAQ vient d'apparaitre. Bonne journée !
