### ISSUE TITLE
Barres de défilement

### ISSUE THREAD

**Issue by fm89** [marion-paclot/DVF#40]
Depuis la mise en production du correctif pour la barre de défilement à droite, mon navigateur m'affiche deux barres inutiles (une dans le menu de gauche et une sur la page entière). Voir la capture ci-dessous.

![image](https://user-images.githubusercontent.com/47399735/57160141-375a0f00-6de8-11e9-9c25-2c8406d77e6f.png)

Pour reproduire : démarrer l'application sans rien faire.

Windows 7 / Chrome Version 74.0.3729.131 (Build officiel) (64 bits) / Toutes tailles de fenêtre

**Comment by marion-paclot** [comment]
@fm89, je te laisse faire la pr, tu as sans aucun doute une idée ;)

**Comment by fm89** [comment]
@jdesboeufs @tmerlier Sur ce coup, je laisse les pros

**Comment by jdesboeufs** [comment]
Déploiement temporaire testable ici : https://etalabapp-dvf-pokablwtgg.now.sh
