### ISSUE TITLE
Filtrage sur les dates en JS ?

### ISSUE THREAD

**Issue by fm89** [marion-paclot/DVF#41]
Quitte à continuer à optimiser le nombre de requêtes servies par le cache Nginx, pourquoi ne pas retirer les paramètres de plage temporelle de la route `/api/mutations2/` et laisser le client JavaScript faire lui-même le filtrage ?

**Comment by marion-paclot** [comment]
@jdesboeufs tu en parlais

**Comment by jdesboeufs** [comment]
Voici une PR qui fait ça :)
