### ISSUE TITLE
Le javascript mélange toutes les mutations d'une parcelle

### ISSUE THREAD

**Issue by asirinelli** [marion-paclot/DVF#44]
Lorsqu'on sélectionne une parcelle avec plusieurs mutations différentes (dans le cas d'une copropriété par exemple), chaque mutation se voit affecter tous les lots de toutes les mutations. Ainsi le contenu des toutes les mutations est identique et comprends tous les lots (seuls les valeurs foncières et date de mutation diffèrent).

A priori l'erreur est dans la partie javascript, car les données retournées par l'API semblent correctes (id_mutation différents). Par exemple, un appel à https://app.dvf.etalab.gouv.fr/api/mutations2/75107/000BM/from=01-01-2014&to=31-12-2018 puis un filtre sur la parcelle 0037 montre bien des mutations différentes alors que le site liste les même lots pour chaque mutation.

**Comment by jdesboeufs** [comment]
Good catch!
C'est corrigé.

Merci
