### ISSUE TITLE
Une API est-elle prévue?

### ISSUE THREAD

**Issue by FrancoisM** [marion-paclot/DVF#7]
Bonjour,

Cet "issue" n'en est pas une.
Je voudrais juste savoir si une API est prévue?
Merci.

François

**Comment by johanricher** [comment]
Une "mini API" est fournie par @cquest : http://api.cquest.org/dvf
Documentée ici : http://data.cquest.org/dgfip_dvf/LISEZ_MOI.txt

**Comment by gonzalodrobles** [comment]
Savez-vous s'il existe une api graphql ?
