### ISSUE TITLE
Pas de date de mutation pour 2018

### ISSUE THREAD

**Issue by Olinsa67** [marion-paclot/DVF#8]
Bonjour,

Pour une commune comme Orchies (59), sur plusieurs sections de cadastre, je n'ai aucune date de mutation pour 2018 (jusque fin juin pour cette année-là), tout s'arrête à fin 2017...
Est-ce normal ? Les données sont-elles manquantes ou ne sont pas remontées par "l'app" ?
Merci.
Cordialement

**Comment by marion-paclot** [comment]
Deux hypothèses : 
1) le format des dates a changé (du genre 01/01/2018 à 2018-01-01), cela se produit sans doute puisque certaines transactions ont des dates "undefined" --> C'est sur ma to-do prioritaire.
2) la remontée des transactions est lente. On n'a des données que jusqu'au 30 juin 2018, mais bien moins de transactions que la moitié de l'année précédente, ce qui laisse penser qu'il en manque encore beaucoup pour la période du 1er janvier au 30 juin.

**Comment by marion-paclot** [comment]
Pas de problème sur les dates. On retient donc la seconde hypothèse.

**Comment by marion-paclot** [comment]
Erreur de ma part : je travaille sur des fichiers qui ont depuis été mis à jour. Je recharge la base complète dans la soirée (j'en ai profitée pour réincorporer des transactions de communes nouvelles). Désolée pour la confusion.

**Comment by marion-paclot** [comment]
Corrigé, enfin :(
