### ISSUE TITLE
DVF pour les dates antérieures à 2014

### ISSUE THREAD

**Issue by olmartinez** [marion-paclot/DVF#9]
Bonjour,

Fantastique initiative ! 
Ce n'est probablement pas une "issue", mais j'ai remarqué que les données n'étaient pas disponible avant 2014. 
Est-il prévu de les ajouter ? 

Olivier

**Comment by marion-paclot** [comment]
Bonjour Olivier
Je ne vais pas m'engager pour la DGFip, mais sans doute que non. En effet, à chaque màj, tous les 6 mois, les 6 mois les plus anciens sortiront pour être remplacés par les plus récents (libre à vous d'archiver dès maintenant). Donc je ne les imagine pas changer cette logique.
